rerun: Use consolidated shell functions for Configi.

diff --git a/rerun/file/commands/directory/script b/rerun/file/commands/directory/script
--- a/rerun/file/commands/directory/script
+++ b/rerun/file/commands/directory/script
@@ -19,20 +19,25 @@ rerun_options_parse "$@"
 # - - -
 # Put the command implementation here.
 # - - -
+
+. "$RERUN_MODULES/lib/configi.sh" "file.directory" || {
+  echo >&2 "Failed loading Configi library." ; exit 1 ;
+}
+
 owner=${OWNER:-root}
 mode=${MODE:-755}
 if [ -d "$ARG" ]; then
-    PASS "file.directory" "$ARG"
+    PASS "$ARG"
     exit 0
 fi
 mkdir -p "$ARG"
 chown "$owner" "$ARG"
 chmod "$mode" "$ARG"
 if [ -d "$ARG" ]; then
-    REPAIR "file.directory" "$ARG"
+    REPAIR "$ARG"
     exit 0
 else
-    FAIL "file.directory" "$ARG"
+    FAIL "$ARG"
     exit 1
 fi
 # Done. Exit with last command exit status.
